database:
  host: localhost
  port: 3306
  username: root
  password: root
  name: test_db 
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 10s
  timezone: UTC
  charset: utf8mb4
  parseTime: true

redis:
  host: localhost
  port: 6379
  password: root
  db: 0

asynQ:
  redisConfig:
    host: localhost
    port: 6379
    password: root
    db: 1
  concurrency: 10